# Locust metrics for SCENARIO=ee-builder-new (test/ee-builder-new.py).

- name: total_requests
  monitoring_query: sum(locust_requests_num_requests{namespace="{{ LOCUST_NAMESPACE }}", job="{{ SCENARIO }}-test-master"})
  monitoring_step: 15
{%macro results_scenario(name) -%}
- name: results.{{ name | replace('-', '_') | replace('.', '_') }}.locust_requests_avg_response_time
  monitoring_query: max(locust_requests_avg_response_time{name=~"[[]{{name}}[]].*", namespace="{{ LOCUST_NAMESPACE }}", job="{{ SCENARIO }}-test-master"})
  monitoring_step: 15
- name: results.{{ name | replace('-', '_') | replace('.', '_') }}.locust_requests_current_rps
  monitoring_query: max(locust_requests_current_rps{name=~"[[]{{name}}[]].*", namespace="{{ LOCUST_NAMESPACE }}", job="{{ SCENARIO }}-test-master"})
  monitoring_step: 15
- name: results.{{ name | replace('-', '_') | replace('.', '_') }}.locust_requests_num_failures
  monitoring_query: sum(locust_requests_num_failures{name=~"[[]{{name}}[]].*", namespace="{{ LOCUST_NAMESPACE }}", job="{{ SCENARIO }}-test-master"})
  monitoring_step: 15
- name: results.{{ name | replace('-', '_') | replace('.', '_') }}.locust_requests_avg_content_length
  monitoring_query: max(locust_requests_avg_content_length{name=~"[[]{{name}}[]].*", namespace="{{ LOCUST_NAMESPACE }}", job="{{ SCENARIO }}-test-master"})
  monitoring_step: 15
{%- endmacro %}

{{ results_scenario('auth') }}
{{ results_scenario('eb.catalog.ee_defs') }}
{{ results_scenario('eb.catalog.templates') }}
{{ results_scenario('eb.catalog.collections') }}
{{ results_scenario('eb.catalog.components') }}
{{ results_scenario('eb.catalog.git') }}
{{ results_scenario('eb.scaffolder.template') }}
{{ results_scenario('eb.scaffolder.autocomplete.search') }}
{{ results_scenario('eb.scaffolder.autocomplete.list') }}
{{ results_scenario('eb.scaffolder.tasks') }}
