apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${SCENARIO}-test-metrics
  namespace: ${LOCUST_NAMESPACE}
  labels:
    app: locust-test
    scenario: ${SCENARIO}

    monitoring.openshift.io/collection-profile: full
    openshift.io/user-monitoring: "true"
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus-metrics
  namespaceSelector:
      matchNames:
        - ${LOCUST_NAMESPACE}
  selector:
    matchLabels:
      app: locust-test
      scenario: ${SCENARIO}
