apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${SCENARIO}-test-metrics
  namespace: ${LOCUST_NAMESPACE}
  labels:
    app: locust-test
    scenario: ${SCENARIO}
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus-metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
      - ${LOCUST_NAMESPACE}
  selector:
    matchLabels:
      scenario: ${SCENARIO}